const actionType = {
    ADD_TO_CART: 'ADD_TO_CART',
    DETELE_FROM_CART: 'DETELE_FROM_CART',
    UPDATE_CART: 'UPDATE_CART',
    DELETE_ALL_CART: 'DELETE_ALL_CART',
    FETCH_NEW_PRODUCT: 'FETCH_NEW_PRODUCT',
    FETCH_HOT_PRODUCT: 'FETCH_HOT_PRODUCT',
    ABATE: 'ABATE',
    SEARCH: 'SEARCH'
}

export default actionType;