const actionType = {
    ADD_TO_CART: 'ADD_TO_CART',
    DETELE_FROM_CART: 'DETELE_FROM_CART',
    FETCH_NEW_PRODUCT: 'FETCH_NEW_PRODUCT',
    FETCH_HOT_PRODUCT: 'FETCH_HOT_PRODUCT',

}

export default actionType;